feat: first iteration of the AACOT'23 website implementation
asyncapi/conference-website pull request #157
Opened 2023-07-27 00:30 UTC by AceTheCreator

This is the first implementation of the AsyncAPI conference website which includes the following.

- Index page
- Venues Page
- Speakers Component
- Venue Component
- The Globe with the pinned event location

cc @thulieblack @Mayaleeeee @derberg @Barbanio @alequetzalli

2023-07-27 07:58 UTC, thulieblack commented
This looks 🤩🤩🤩🤩🤩🤩

2023-07-27 08:18 UTC, thulieblack reviewed
We'll be doing 4 events this year instead of 5 thus why we not going to include Melbourne

2023-07-27 08:18 UTC, thulieblack commented on config/city-lists.json
> +		"address": "TBH"
```suggestion
		"address": "TBA"
```

2023-07-27 08:18 UTC, thulieblack commented on config/city-lists.json
> +	}
```suggestion
	
```

2023-07-27 08:18 UTC, thulieblack commented on config/city-lists.json
> +	},
```suggestion
	}
```

2023-07-27 08:18 UTC, thulieblack commented on config/city-lists.json
> +	{
```suggestion
	
```

2023-07-27 08:18 UTC, thulieblack commented on config/city-lists.json
> +		"name": "Melbourne",
```suggestion
```

2023-07-27 08:18 UTC, thulieblack commented on config/city-lists.json
> +		"country": "Australia",
```suggestion
```

2023-07-27 08:18 UTC, thulieblack commented on config/city-lists.json
> +		"description": "Join us in Madrid for AsyncAPI Conference and learn how to speak fluent API! Let's taco 'bout messaging and have a fiesta you won't forget!",
```suggestion

```

2023-07-27 08:18 UTC, thulieblack commented on config/city-lists.json
> +		"img": "https://images.unsplash.com/photo-1470294402047-fc1b5f39bd99?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2374&q=80",
```suggestion

```

2023-07-27 08:18 UTC, thulieblack commented on config/city-lists.json
> +		"address": "TBH"
```suggestion

```

2023-07-27 08:18 UTC, thulieblack commented on config/links.json
> +			},
```suggestion
			}
```

2023-07-27 08:18 UTC, thulieblack commented on config/links.json
> +				"title": "Melbourne, Australia",
```suggestion
```

2023-07-27 08:18 UTC, thulieblack commented on config/links.json
> +			{
```suggestion
```

2023-07-27 08:18 UTC, thulieblack commented on config/speakers.json
> +	},
```suggestion
	}
```

2023-07-27 08:18 UTC, thulieblack commented on config/speakers.json
> +		"lists": []
```suggestion
```

2023-07-27 08:18 UTC, thulieblack commented on config/speakers.json
> +	}
```suggestion
```

2023-07-27 08:24 UTC, thulieblack commented on config/city-lists.json
> +		"address": "TBH"
```suggestion
		"address": "Centre des Nouvelles Industries et Technologies, 2 Place de la Défense, 92092 Puteaux, Paris"
```

2023-07-27 08:27 UTC, thulieblack commented on config/city-lists.json
> +		"description": "Join us in Madrid for AsyncAPI Conference and learn how to speak fluent API! Let's taco 'bout messaging and have a fiesta you won't forget!",
```suggestion
		"description": "Join us in Paris for the AsyncAPI Conference and learn more about APIs and EDAs! Let's have a memorable fiesta!",
```

2023-07-27 08:28 UTC, thulieblack commented on config/city-lists.json
> +		"description": "Join us in Madrid for AsyncAPI Conference and learn how to speak fluent API! Let's taco 'bout messaging and have a fiesta you won't forget!",
```suggestion
		"description": "Join us in Bangalore for the AsyncAPI Conference and learn more about APIs and EDAs! Let's have a memorable fiesta!",
```

2023-07-28 12:47 UTC, AceTheCreator commented
PR updated @thulieblack

2023-07-31 10:27 UTC, thulieblack commented on config/city-lists.json
> +		"date": "October 26, 2023",
```suggestion
		"date": "October 18-19, 2023",
```

2023-07-31 10:28 UTC, thulieblack commented on config/city-lists.json
> +		"date": "September 26, 2023",
```suggestion
		"date": "September 20, 2023",
```

2023-07-31 10:40 UTC, thulieblack requested changes
1. Let's remove Melbourne from the venue page and add London
![image](https://github.com/asyncapi/conference-website/assets/66913810/4be3df5a-e0c7-4162-b633-4c7c76c64249)
2. Lets remove this from the London Speakers page 
![image](https://github.com/asyncapi/conference-website/assets/66913810/832e4c93-76d7-4603-a0e9-97e0712e3fae)
3. Correct the dates for London - 20th of September Madrid is either 18 or 19 October _(will update later on)_
4. This is a suggestion. Is there a way we can fill the upper part of the rotating globe? Instead of seeing half, it'll be full? 
![image](https://github.com/asyncapi/conference-website/assets/66913810/b0fa39ed-b965-4ab0-b0ff-3aa4f75075f1)
5. When using a mobile phone the globe is not visible too

2023-07-31 10:46 UTC, thulieblack commented on config/links.json
> +			},
```suggestion
			},
			{
				"title": "London, UK",
				"ref": "/venue/London"
			},
```

2023-07-31 14:32 UTC, AceTheCreator commented
> This is a suggestion. Is there a way we can fill the upper part of the rotating globe? Instead of seeing half, it'll be full?

This was intentional for aesthetics. 

> When using a mobile phone the globe is not visible too

This is also intentional as we need the site to load as fast as possible on mobile devices.

2023-08-01 09:53 UTC, Mayaleeeee commented
Thanks for working on this @AceTheCreator, you did a fantastic job, and I love it. However, I have a few comments based on what I have noticed. 

- There is no interaction on the card here (e.g. hovered and selected)

![Screenshot 2023-08-01 103208](https://github.com/asyncapi/conference-website/assets/105395613/115cb8ed-b6bf-45f8-91d0-b72c75ad1d6c)

- The texts under the location here are supposed to be centred-aligned, not left-aligned
![Screenshot 2023-08-01 103430](https://github.com/asyncapi/conference-website/assets/105395613/2bc5d10e-210d-4e0b-9d89-373bb8f377a6)

Under this same page, we also mentioned that we should add a section where users will see the event/host sponsors of the location immediately after they enter the page, it's on the design I created (see the picture below), but it's not on the deploy-preview

![Screenshot 2023-08-01 104141](https://github.com/asyncapi/conference-website/assets/105395613/9e6ad236-f81c-487b-9d55-406269fc5dff)

- Also, the links here should take us to our social media pages
![Screenshot 2023-08-01 104326](https://github.com/asyncapi/conference-website/assets/105395613/da52fccf-6a60-4e41-be42-e7df0708e3d2)

- The texts here are not well aligned, and even though they are still the same thing, the first one is 
![Screenshot 2023-08-01 104749](https://github.com/asyncapi/conference-website/assets/105395613/d285fecc-c666-475b-aecd-0d8639388e14)
under London, UK (looks bigger than the rest of it).

I think that's all I have noticed for now; if I see anything else, I will update this thread. 

Please let me know if there's anything you would like me to do from the design aspect. Thank you so much  @AceTheCreator

2023-08-01 13:13 UTC, AceTheCreator commented
>under London, UK (looks bigger than the rest of it).

I don't understand what you're talking about

2023-08-03 13:48 UTC, thulieblack commented
@AceTheCreator here is something for the Madrid page https://www.youtube.com/watch?v=SyZpHbWK5b4

2023-08-07 07:42 UTC, Mayaleeeee commented
> > Under this same page, we also mentioned that we should add a section where users will see the event/host sponsors of the location immediately after they enter the page, it's on the design I created (see the picture below), but it's not on the deploy-preview
> 
> @Mayaleeeee It doesn't make sense to me why we are gonna have the sponsors there and then still have it in another section of the page. That was why I didn't include it.
> 
> The remaining you pointed out(apart from the last one) was all intentional as I also want other contributors to fix this minor issue as a means of contributing to the project

Oh, that's fine then,

2023-08-07 08:02 UTC, Mayaleeeee commented
> > under London, UK (looks bigger than the rest of it).
> 
> I don't understand what you're talking about

Hey @AceTheCreator, I'm trying to explain that "Join us in London for AsyncAPI ..." appears larger than the sentences beneath Madrid and Bangaluru in the picture below. Despite containing the exact text, the London sentence seems larger. Also, you'll notice that the London sentence covers four lines, while the others only cover three. Do you now understand my point?

![257476100-d285fecc-c666-475b-aecd-0d8639388e14](https://github.com/asyncapi/conference-website/assets/105395613/8799aebb-bd13-4ecf-870e-057283668cec)

2023-08-07 08:13 UTC, AceTheCreator commented
> > > under London, UK (looks bigger than the rest of it).
> > 
> > 
> > I don't understand what you're talking about
> 
> Hey @AceTheCreator, I'm trying to explain that **"Join us in London for AsyncAPI ..."** appears larger than the sentences beneath Madrid and Bangaluru in the picture below. Despite containing the exact text, the London sentence seems larger. Also, you'll notice that the London sentence covers four lines, while the others only cover three. Do you now understand my point?
> 
> ![257476100-d285fecc-c666-475b-aecd-0d8639388e14](https://user-images.githubusercontent.com/105395613/258737533-8799aebb-bd13-4ecf-870e-057283668cec.png)

@Mayaleeeee the text beneath London is not the same length as the rest

2023-08-07 08:16 UTC, Mayaleeeee commented
> > > > under London, UK (looks bigger than the rest of it).
> > > 
> > > 
> > > I don't understand what you're talking about
> > 
> > Hey @AceTheCreator, I'm trying to explain that **"Join us in London for AsyncAPI ..."** appears larger than the sentences beneath Madrid and Bangaluru in the picture below. Despite containing the exact text, the London sentence seems larger. Also, you'll notice that the London sentence covers four lines, while the others only cover three. Do you now understand my point?
> > 
> > ![257476100-d285fecc-c666-475b-aecd-0d8639388e14](https://user-images.githubusercontent.com/105395613/258737533-8799aebb-bd13-4ecf-870e-057283668cec.png)
> 
> @Mayaleeeee the text beneath London is not the same length as the rest

Exactly my point, it's supposed to be the same length since the only difference there is the name of the location.

2023-08-07 08:28 UTC, thulieblack commented
To solve this, is there a way we can align everything to the same width and height? That might solve the issue Maya is pointing out and make everything be in uniform

2023-08-07 11:09 UTC, AceTheCreator commented
Pr updated! @thulieblack @Mayaleeeee @derberg

2023-08-07 11:27 UTC, thulieblack commented
1. Madrid is now 19 October 
2. We need to improve mobile usability (at a later stage)

2023-08-07 12:01 UTC, AceTheCreator commented
> 1. Madrid is now 19 October
> 2. We need to improve mobile usability (at a later stage)

Updated!

2023-08-07 12:30 UTC, Barbanio commented
Hi, sorry for the delay.

@AceTheCreator, good job! It looks great!

1. When I use the menu, it remains on the screen, and I must close it manually. 

2. In the mobile version, in the Venues section, the text and images are cut off on the right side. 

![IMG](https://github.com/asyncapi/conference-website/assets/77982319/f8cd7efd-285e-4f90-8267-441a7b182648)

2023-08-07 12:46 UTC, AceTheCreator commented
> In the mobile version, in the Venues section, the text and images are cut off on the right side.

@Barbanio at what screen resolution is this?

2023-08-07 12:56 UTC, Barbanio commented
1334x750px (326 ppp)

2023-08-07 13:06 UTC, AceTheCreator commented
> 1334x750px (326 ppp)

Is it the last preview on the list?

2023-08-07 13:13 UTC, Barbanio commented
> Is it the last preview on the list?

Yes

2023-08-07 13:30 UTC, AceTheCreator commented
> > Is it the last preview on the list?
> 
> Yes

Oh! this was because I didn't include an infinity scroll. Fixed!

2023-08-07 15:08 UTC, Mayaleeeee commented
1. The Madrid button should be active once the users reach the speaker section since that's the first set of speakers they will see.

![Screenshot 2023-08-07 160238](https://github.com/asyncapi/conference-website/assets/105395613/27a97887-f1fd-4a73-83e9-9bf4360f5355)

2. The subscribe button here takes me to another page: **"Subscribe to our newsletter to receive news about AsyncAPI."** Is that intentional?

![Screenshot 2023-08-07 160401](https://github.com/asyncapi/conference-website/assets/105395613/f0244ade-3b35-474d-b585-3e397df04be7)

2023-08-07 15:29 UTC, Mayaleeeee commented
> > Under this same page, we also mentioned that we should add a section where users will see the event/host sponsors of the location immediately after they enter the page, it's on the design I created (see the picture below), but it's not on the deploy-preview
> 
> @Mayaleeeee It doesn't make sense to me why we are gonna have the sponsors there and then still have it in another section of the page. That was why I didn't include it.
> 
> The remaining you pointed out(apart from the last one) was all intentional as I also want other contributors to fix this minor issue as a means of contributing to the project

We can reduce the whitespace since we won't add the event/host sponsors here.
![Screenshot 2023-08-07 162359](https://github.com/asyncapi/conference-website/assets/105395613/bc478525-f47e-40ec-bfeb-1321dfd1644e)

2023-08-07 15:42 UTC, thulieblack commented on config/city-lists.json
> +		"date": "TBA",
```suggestion
		"date": "November 30, 2023",
```

2023-08-07 15:44 UTC, thulieblack commented on config/city-lists.json
> +		"address": "309, Venkatesh complex, floor, 100 feet road, Indiranagar, Bangalore, Karnataka 560038, India"
```suggestion
		"address": "310, 6th Main Rd, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038, India"
```

2023-08-07 16:08 UTC, Mayaleeeee commented
For each of the locations, we could have something like this:
 
 1. Madrid:
   Join us in **Madrid** for AsyncAPI Conference and learn how to speak fluent API! Let's taco about messaging and have a fiesta you will remember!

2. London:
   Join us in **London** for the AsyncAPI Conference and unlock the API of opportunities! Let's bridge the messaging gap and create a tech buzz you will want to experience!

3. Paris:
   Join us in **Paris** for the AsyncAPI Conference and experience the art of API perfection! Let's craft a symphony of messaging and celebrate tech in style!"

4. Bengaluru:
   Join us in **Bengaluru** for the AsyncAPI Conference and decode the language of APIs! Let's crack the language of APIs and ignite a tech revolution with some spice you'll remember!

The names of the locations will be displayed **in bold and in the same colour as the date.** This signifies that they are clickable. Users can click on the location name or the accompanying image to access the corresponding page directly. I recommend this approach to avoid confusion caused by the phrase **'Join us,'** which begins each location's description.  

I'd like more suggestions and would appreciate your input on this approach. @AceTheCreator @thulieblack @derberg @Barbanio

2023-08-07 16:44 UTC, AceTheCreator commented
> > > Under this same page, we also mentioned that we should add a section where users will see the event/host sponsors of the location immediately after they enter the page, it's on the design I created (see the picture below), but it's not on the deploy-preview
> > 
> > 
> > @Mayaleeeee It doesn't make sense to me why we are gonna have the sponsors there and then still have it in another section of the page. That was why I didn't include it.
> > The remaining you pointed out(apart from the last one) was all intentional as I also want other contributors to fix this minor issue as a means of contributing to the project
> 
> We can reduce the whitespace since we won't add the event/host sponsors here. ![Screenshot 2023-08-07 162359](https://user-images.githubusercontent.com/105395613/258850054-bc478525-f47e-40ec-bfeb-1321dfd1644e.png)
> 
done!
> I realized the map on the location page is on the preview website. Was that intentional? ![Screenshot 2023-08-07 163039](https://user-images.githubusercontent.com/105395613/258850965-17fd5885-e818-4067-9c3b-c5b6b16b50bf.png)

This is also intentional. It will come as a contribution.

2023-08-07 17:00 UTC, Mayaleeeee commented
> > 1. The Madrid button should be active once the users reach the speaker section since that's the first set of speakers they will see.
> > 
> 
> This is intentional, as suggested by @derberg we should render all speakers by default and then by clicking you filter by region
> > ![Screenshot 2023-08-07 160238](https://user-images.githubusercontent.com/105395613/258844056-27a97887-f1fd-4a73-83e9-9bf4360f5355.png)
> > 
> > 2. The subscribe button here takes me to another page: **"Subscribe to our newsletter to receive news about AsyncAPI."** Is that intentional?
> > 
> 
> Yea, this is also intentional as we don't have the bandwidth to maintain a different newsletter for conference
> 
> > ![Screenshot 2023-08-07 160401](https://user-images.githubusercontent.com/105395613/258844437-f0244ade-3b35-474d-b585-3e397df04be7.png)
> 
> 

We should have a "All" button then.
What do you think?

2023-08-07 18:29 UTC, thulieblack commented
Hey @Mayaleeeee, the newsletter details are fine as it is. The monthly newsletter shipped out every month will contain all the necessary information about all the conferences

2023-08-07 18:36 UTC, Mayaleeeee commented
> Hey @Mayaleeeee, the newsletter details are fine as it is. The monthly newsletter shipped out every month will contain all the necessary information about all the conferences

Ohh, that's cool then.

2023-08-08 09:13 UTC, AceTheCreator commented
I think this PR is rtm cc @derberg @thulieblack @Mayaleeeee @Barbanio

2023-08-08 13:01 UTC, Mayaleeeee commented
> I think this PR is rtm cc @derberg @thulieblack @Mayaleeeee @Barbanio

I apologize, @AceTheCreator, but there seems to be a misunderstanding. I was actually referring to the specific locations marked in the screenshot below and not the **main location header.**

![Screenshot 2023-08-08 135904](https://github.com/asyncapi/conference-website/assets/105395613/1890e0fe-5289-48be-8e6c-13895d622b21)

2023-08-08 13:02 UTC, Mayaleeeee commented
> lgtm, I personally do not spend much time on websites to be patient enough to wait for entire globe animation, and see how new cities and countdown shows up. I personally would prefer to show all locations and countdowns by default (and they can highlight or whatever one after another if you want). But if I'm the only one and others like how it is now, I won't block.
> 
> Great stuff @AceTheCreator 🚀 @Mayaleeeee you've got a pretty nice production implementation of your design for your portfolio, well done 👏🏼

Thank you so much.
Well done @AceTheCreator

2023-08-08 13:05 UTC, AceTheCreator commented
> > I think this PR is rtm cc @derberg @thulieblack @Mayaleeeee @Barbanio
> 
> I apologize, @AceTheCreator, but there seems to be a misunderstanding. I was actually referring to the specific locations marked in the screenshot below and not the **main location header.**
> 
> ![Screenshot 2023-08-08 135904](https://user-images.githubusercontent.com/105395613/259106127-1890e0fe-5289-48be-8e6c-13895d622b21.png)

Oh! If that's what you meant, then I don't think that will be necessary because making the whole card clickable is the best UX IMHO not the text within a sentence. I'll change the title back to white :)

2023-08-08 19:24 UTC, Mayaleeeee commented
> > > I think this PR is rtm cc @derberg @thulieblack @Mayaleeeee @Barbanio
> > 
> > 
> > I apologize, @AceTheCreator, but there seems to be a misunderstanding. I was actually referring to the specific locations marked in the screenshot below and not the **main location header.**
> > ![Screenshot 2023-08-08 135904](https://user-images.githubusercontent.com/105395613/259106127-1890e0fe-5289-48be-8e6c-13895d622b21.png)
> 
> Oh! If that's what you meant, then I don't think that will be necessary because making the whole card clickable is the best UX IMHO not the text within a sentence. I'll change the title back to white :)

Sure, that works as well. My worry was about the main location header, and I can see that you have adjusted the color. Thank you.

2023-08-09 10:24 UTC, thulieblack approved these changes
looks good; let's get the 1st iteration merged!!

2023-08-09 12:03 UTC, derberg commented
merge merge merge and in a follow up PR I guess it is a right time to add CODEOWNERS

2023-08-09 12:34 UTC, Mayaleeeee commented
:partying_face: :partying_face: :partying_face:

2023-08-09 12:35 UTC, Mayaleeeee commented
🥳🥳🥳🌸

2023-08-09 13:50 UTC, merged