feat: preparation for 2024 conference on tour
asyncapi/conference-website pull request #263
Opened 2024-02-21 13:12 UTC by AceTheCreator

This PR contains the initial requirement for the 2024 conference

2024-02-22 11:22 UTC, thulieblack requested changes
1. hey @AceTheCreator would it be possible to remove the "AsyncAPI v3 button and replace it with "Call for Speakers Now Open" and redirect the link to the Helsinki Page?
![image](https://github.com/asyncapi/conference-website/assets/66913810/cb0219f6-81c2-4fdb-9243-ee0069671504)
2. Make this CfP a bit bigger its hardly noticeable 
![image](https://github.com/asyncapi/conference-website/assets/66913810/7bac3a25-dfda-46b7-8d34-87d1178af47d)
3. Can we add a paragraph: "We are currently looking for sponsors, for more details please read our Sponsorship Prospectus"
![image](https://github.com/asyncapi/conference-website/assets/66913810/8da6c3eb-1ea1-46e5-917c-b8e3f75c1215)
4. Finally, you can open up the Call for Speakers/Submit your Proposal, for London and Paris as well. Using the same link

2024-02-22 11:22 UTC, thulieblack commented on config/city-lists.json
> +		"description": "Join us in Helsinki for the AsyncAPI Conference and unlock the API of opportunities! Let's bridge the messaging gap and create a tech buzz you will want to experience!",
```suggestion
		"description": "Join us in Helsinki for the AsyncAPI Conference, where we will explore all things AsyncAPI and connect physical and digital worlds. Get excited as we delve into sustainable APIs for the Era of AI, Data Platforms, and Quantum Computing!.",
```

2024-02-22 16:13 UTC, thulieblack commented
cc @Mayaleeeee

2024-02-22 16:14 UTC, Mayaleeeee commented
> cc @Mayaleeeee 

I'm on it

2024-02-27 21:39 UTC, Mayaleeeee commented
- The texts on the location images are difficult to read.

![h](https://github.com/asyncapi/conference-website/assets/105395613/d1c0231a-68c9-4a00-9f4e-8084c3be1428)

Instead, we could have something like the one below; you can check it in the Figma file [here](https://www.figma.com/file/sS5ofLRtuFqDGFvlNBurns/AsyncAPI-Conference-on-Tour'23%2FAACoT?type=design&node-id=1457%3A1002&mode=design&t=MkiKZWZHWuXJFlDO-1).
![Paris](https://github.com/asyncapi/conference-website/assets/105395613/eb5e4154-a118-4461-a77a-525206d6dbfe)

2024-02-27 21:45 UTC, Mayaleeeee commented
- the distance between the elements in the hero section should be the same length as the [previous year](https://conference.asyncapi.com/). 

![Screenshot 2024-02-27 224431](https://github.com/asyncapi/conference-website/assets/105395613/36af95c1-bdba-4fc8-8e23-1a30d4bf5dd6)

2024-03-05 00:02 UTC, AceTheCreator commented
@Mayaleeeee, fantastic suggestions but I'd love to propose them gfi once we merge this PR. wyt?

2024-03-05 08:55 UTC, thulieblack approved these changes

2024-03-05 08:57 UTC, thulieblack commented
/rtm

2024-03-05 09:15 UTC, merged