fix: dropdown and the contents of the dropdown section
asyncapi/conference-website pull request #347
Opened 2024-07-17 20:08 UTC by sbsangu

**Description**

- **Bug Description:** The dropdown icon does not show, and the 'All' text is aligned to the left side and the dropdown is not working properly.
- **Expected Behavior:** The dropdown icon should be shown, and the inner content of the button should be centered and the dropdown should work as expected.
- **Fix Implemented:** 
  - Added missing dropdown icon to the button.
  - Centered the text inside the button to align properly.
  - Fixed the dropdown functionality.

![Screenshot 2024-07-18 013654](https://github.com/user-attachments/assets/0449bd31-afe2-4bf1-87a3-dd582e7e3195)

Fixes #345

2024-07-22 10:31 UTC, AceTheCreator commented
@sbsangu, Thanks for opening the PR. I'll have to hold on reviewing the PR cuz the discussion in the issue doesn't seem to be resolved yet

2024-07-30 05:37 UTC, sbsangu commented
@AceTheCreator  Does the discussion in the issue is resolved?

2024-08-01 14:56 UTC, AceTheCreator commented
Not yet, still waiting for @Mayaleeeee comments.

2024-08-21 11:13 UTC, Mayaleeeee approved these changes
Looks good, @sbsangu  Thank you!

cc @AceTheCreator @ashmit-coder

2024-08-21 11:46 UTC, AceTheCreator commented
@sbsangu,two things.
- You don't have to make the dropdown border-radius that curved.
- Dropdown doesn't close when i click out.

2024-08-21 12:11 UTC, Mayaleeeee commented
> @sbsangu,two things.
> 
> * You don't have to make the dropdown border-radius that curved.
> * Dropdown doesn't close when i click out.

Hey @AceTheCreator 
Typically, dropdowns can close when clicking outside. It keeps the UI clean and reduces user confusion. I'm curious, though, what's your reason for not supporting that behaviour? I'd love to understand your perspective.

2024-09-02 17:57 UTC, sbsangu commented
@AceTheCreator @Mayaleeeee  Do i need to change anything?

2024-09-05 12:34 UTC, AceTheCreator commented
> > @sbsangu,two things.
> > 
> > * You don't have to make the dropdown border-radius that curved.
> > * Dropdown doesn't close when i click out.
> 
> Hey @AceTheCreator Typically, dropdowns can close when clicking outside. It keeps the UI clean and reduces user confusion. I'm curious, though, what's your reason for not supporting that behaviour? I'd love to understand your perspective.

Sorry, what behaviour @Mayaleeeee?

2024-09-05 15:27 UTC, Mayaleeeee commented
> > > @sbsangu,two things.
> > > 
> > > * You don't have to make the dropdown border-radius that curved.
> > > * Dropdown doesn't close when i click out.
> > 
> > Hey @AceTheCreator Typically, dropdowns can close when clicking outside. It keeps the UI clean and reduces user confusion. I'm curious, though, what's your reason for not supporting that behaviour? I'd love to understand your perspective.
> 
> Sorry, what behaviour @Mayaleeeee? 

I mean what's your reason for not supporting the changes. @AceTheCreator

2024-10-10 16:20 UTC, AceTheCreator commented
> > > > @sbsangu,two things.
> > > > 
> > > > * You don't have to make the dropdown border-radius that curved.
> > > > * Dropdown doesn't close when i click out.
> > > 
> > > 
> > > Hey @AceTheCreator Typically, dropdowns can close when clicking outside. It keeps the UI clean and reduces user confusion. I'm curious, though, what's your reason for not supporting that behaviour? I'd love to understand your perspective.
> > 
> > 
> > Sorry, what behaviour @Mayaleeeee?
> 
> I mean what's your reason for not supporting the changes. @AceTheCreator

I do support the changes, i'm only suggesting enhancements :/ If you think it's looks good, we are good to go.

2024-10-30 11:06 UTC, AceTheCreator requested changes
Can you resolve the conflict?

2024-11-02 17:23 UTC, ashmit-coder commented
cc : @sbsangu

2024-11-10 10:18 UTC, ashmit-coder commented
I guess we should close this pr @AceTheCreator .

2025-01-24 11:04 UTC, sbsangu commented
cc: @AceTheCreator , @ashmit-coder

2025-03-09 12:01 UTC, AceTheCreator commented
I'm going to have to close this PR 🙏🏽

2025-03-09 12:01 UTC, closed without merging