feat: disable london ticket button
asyncapi/conference-website pull request #390
Opened 2024-09-15 09:17 UTC by thulieblack

2024-09-16 10:47 UTC, AceTheCreator requested changes
I don't think you should remove the ticket url. Just changing the ended value will do :)

2024-09-17 05:57 UTC, thulieblack commented on config/city-lists.json
> +		"ticket": false,
```suggestion
		"ticket": "https://ticket.apidays.global/event/apidays-london-2024/869eca20-bfb6-4103-b8bb-d0348932e940/",
```

2024-09-17 06:00 UTC, thulieblack commented
/rtm

2024-09-17 06:00 UTC, merged

2024-09-17 06:07 UTC, thulieblack commented
tickets sold out has to merge this asap