fix: google font import and allignment of button
asyncapi/conference-website pull request #391
Opened 2024-09-15 09:20 UTC by catosaurusrex2003

Before google fonts were not working as expected because they were not imported at the top most line of our css. And this was causing CSS Parsing Order issue.

also fixed allignment of text inside button

**Changes in FIREFOX:**
![image](https://github.com/user-attachments/assets/0b73a913-027c-44b7-a488-0be7a5817d57)
👆 Before

![image](https://github.com/user-attachments/assets/8cfd030b-878b-466f-9344-02dce141dac4)
👆 After

**Changes in CHROME:**
![image](https://github.com/user-attachments/assets/85b6b095-c8e1-4c4d-9956-f9ad8dab993b)
👆 Before

![image](https://github.com/user-attachments/assets/93c90e9b-86f3-4759-84ee-10b8e8a9398f)
👆 After

I might not have been able to explain it correctly in the following issue #389 
But i hope the code in the PR makes sense.

Fixes issue : #389

2024-09-16 10:45 UTC, AceTheCreator commented
Also the list of venues in the subnav is misaligned

2024-09-16 11:27 UTC, catosaurusrex2003 commented
ok.
i will check for all misalignment issues and fix it in this PR itself.

2024-09-16 17:50 UTC, catosaurusrex2003 commented
I have also noted this issue
![image](https://github.com/user-attachments/assets/19248b11-b91d-457c-b3fe-3cc8f2170cde)
look at the orientation of the + sign of the first item in the image above 👆. I think it should be X but it is slightly awkward.
![image](https://github.com/user-attachments/assets/2e866f35-8bb4-44bb-ae18-848adba533e4)
shouldnt it be like this 👆 ? or is this intended behaviour.

2024-09-20 13:17 UTC, catosaurusrex2003 commented
@AceTheCreator  
/ptal

2024-09-27 11:49 UTC, ashmit-coder commented
> I have also noted this minute thing ![image](https://private-user-images.githubusercontent.com/96487647/367866538-19248b11-b91d-457c-b3fe-3cc8f2170cde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0Mzc5MTksIm5iZiI6MTcyNzQzNzYxOSwicGF0aCI6Ii85NjQ4NzY0Ny8zNjc4NjY1MzgtMTkyNDhiMTEtYjkxZC00NTdjLWIzZmUtM2NjOGYyMTcwY2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDExNDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYmY2ODU2YTVlOTk5MDI1NjJmZTU5NTRlNDI4NGYwOGUxZGQ1ODVhNjgxOTEzODE4NmMxMmEzZWQ0NTc0YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KhIaMqz6k2LKJg8cOc2ekfdUvu79bQcJVYb2T3r95Io) look at the orientation of the + sign of the first item in the image above 👆. I think it should be X but it is slightly awkward. ![image](https://private-user-images.githubusercontent.com/96487647/367866871-2e866f35-8bb4-44bb-ae18-848adba533e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0Mzc5MTksIm5iZiI6MTcyNzQzNzYxOSwicGF0aCI6Ii85NjQ4NzY0Ny8zNjc4NjY4NzEtMmU4NjZmMzUtOGJiNC00NGJiLWFlMTgtODQ4YWRiYTUzM2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDExNDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwOGQ2Mjc3ZmQwYTc3YzFmYjdhODgyM2Q3MDk0M2E4YTBlYjU5OWJjYWQ4YWM4ZTgwNzgzZDAwMDViNzk2OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xUQzam6dFAes2pSUJEME2dqpFh9l395cfJgK7y51XJU) shouldnt it be like this 👆 ? or is this intended behaviour.

It does look better that way @catosaurusrex2003 go ahead with that change!

2024-09-27 11:54 UTC, ashmit-coder requested changes
Hey @catosaurusrex2003 , you seem to have removed the hover effect from the navbar.

Expected:
![Screenshot from 2024-09-27 17-22-58](https://github.com/user-attachments/assets/b90eb2a1-34c1-4e93-a946-752752cba212)

Current:
![Screenshot from 2024-09-27 17-22-04](https://github.com/user-attachments/assets/15663e7a-4693-4a11-9e66-64250a1f0e29)

2024-09-27 16:37 UTC, catosaurusrex2003 commented
Nice observation @ashmit-coder 
Fixed it 👍

2024-10-04 15:50 UTC, ashmit-coder commented
Hey @AceTheCreator are we moving ahead with this pr?

if yes then @catosaurusrex2003 could you please update the branch

2024-10-07 18:59 UTC, AceTheCreator commented
waiting for your approval @ashmit-coder :)

2024-10-07 20:02 UTC, ashmit-coder commented
> Hey @catosaurusrex2003 , you seem to have removed the hover effect from the navbar.
> 
> Expected: ![Screenshot from 2024-09-27 17-22-58](https://private-user-images.githubusercontent.com/69006513/371521778-b90eb2a1-34c1-4e93-a946-752752cba212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMzE1NjcsIm5iZiI6MTcyODMzMTI2NywicGF0aCI6Ii82OTAwNjUxMy8zNzE1MjE3NzgtYjkwZWIyYTEtMzRjMS00ZTkzLWE5NDYtNzUyNzUyY2JhMjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIwMDEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOGNmOWUwOWE2MjMzYjhlZjAzOWJjZTM0ZDRkYjBhMTRjZDA1OTZiZWE0ZDUzYTU1YmUyODk3ZjIzMmIzYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cnBspg-CkzxKHseT7F1DYopZ2iVITIba5jsdvcJJmio)
> 
> Current: ![Screenshot from 2024-09-27 17-22-04](https://private-user-images.githubusercontent.com/69006513/371521833-15663e7a-4693-4a11-9e66-64250a1f0e29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMzE1NjcsIm5iZiI6MTcyODMzMTI2NywicGF0aCI6Ii82OTAwNjUxMy8zNzE1MjE4MzMtMTU2NjNlN2EtNDY5My00YTExLTllNjYtNjQyNTBhMWYwZTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIwMDEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZDA5NmY0ODZjODI1YjIxYmRkYjZjNzdjNGU1MGM5ZDI1ZDQ5Y2U2ZGJjMzA0ODkzMWQzNjhkZWZhZWY5YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UgayCO4UGBGq01W2DXLA8h07pLCzCIJnzzdc05QgADs)

@catosaurusrex2003 could you make the `Helsinki Finlad`. Appear on the same line as it was earlier

2024-10-07 21:15 UTC, catosaurusrex2003 commented
@ashmit-coder @AceTheCreator done

2024-10-08 09:06 UTC, ashmit-coder commented
Hey @catosaurusrex2003 

![image](https://github.com/user-attachments/assets/12e6bdd8-273d-43e8-9083-fe4ac429e453)


fix this alignment issue in the Paris page

2024-10-08 09:07 UTC, ashmit-coder commented
![image](https://github.com/user-attachments/assets/d82a375a-a5ec-46f8-8546-96418a44c4a0)


this as well.

2024-10-08 09:08 UTC, ashmit-coder commented
![image](https://github.com/user-attachments/assets/f72ce43c-c705-42de-8a15-55e3c08167c4)

This as well.

2024-10-08 09:10 UTC, ashmit-coder commented
![image](https://github.com/user-attachments/assets/ff10a9dc-cfc3-49b2-abfc-1e9c0434b30c)

The ticket card also has some issues, do look into it.

2024-10-08 16:11 UTC, catosaurusrex2003 commented
I went through the whole website and now i dont think there are any discrepancies.

If any, pls let me know i will resolve them.

@ashmit-coder

2024-10-09 03:21 UTC, ashmit-coder commented
Hey @catosaurusrex2003 could you check so for mobile view as well?

2024-10-09 09:18 UTC, catosaurusrex2003 commented
done @ashmit-coder 
i hope there isnt anything i missed out again 😆

2024-10-09 13:16 UTC, AceTheCreator approved these changes
LGTM! 🚀

2024-10-09 13:16 UTC, AceTheCreator commented
CC @ashmit-coder

2024-10-09 13:38 UTC, catosaurusrex2003 commented on components/Buttons/button.js
> +			className={`${overlay ? '' : 'gradient-bg'} flex items-center justify-center text-white h-[54px] rounded-md p-[8px] ${className}`}
i am not able to locate any alignment issue.
whats the browser u using? and if possible can you attach the screenshot.

2024-10-09 21:11 UTC, ashmit-coder commented
> CC @ashmit-coder

LGTM!

2024-10-10 16:01 UTC, merged