Add Online Speaker Images and Names
asyncapi/conference-website pull request #409
Opened 2024-10-02 17:07 UTC by techmannih

Close #408 
Issue #408 
@thulieblack please review and merge it.
![Screenshot 2024-10-02 222842](https://github.com/user-attachments/assets/e4ca4306-a77d-41e6-ae82-028e99291cf7)

2024-10-02 17:17 UTC, ashmit-coder commented
hey @techmannih could you into why some of the checks are failing?

2024-10-02 17:19 UTC, ashmit-coder commented
Hey @thulieblack shall we make the images available offline, one pr is dealing with that issue. If we are adding on new images I think it should follow the same convention.

2024-10-02 17:19 UTC, thulieblack commented
The pr is not complete, please add the descriptions for each.

2024-10-02 17:22 UTC, thulieblack commented
Yes @ashmit-coder it should, please give some details on how too

2024-10-02 17:26 UTC, ashmit-coder commented
hey @thulieblack @techmannih 
https://github.com/asyncapi/conference-website/pull/404

lets wait for this issue to get resolved at first IMO. 
If this pr is urgent then lets merge it (after it passes the checks) and later we will raise a new issue to follow the local images convention.

2024-10-02 17:32 UTC, thulieblack commented
Makes sense, the PR isn't ready yet some of the speakers info is missing that's why checks aren't passing

2024-10-02 17:33 UTC, techmannih commented
@ashmit-coder  @thulieblack  there is no description for rest of speakers, so how will I add

2024-10-02 18:13 UTC, ashmit-coder commented
Lets see I am not quite sure why the checks are failing as well.

2024-10-02 18:14 UTC, ashmit-coder commented
> @ashmit-coder @thulieblack there is no description for rest of speakers, so how will I add

I guess @thulieblack means adding the speakers from the last years session ?

2024-10-02 18:18 UTC, techmannih commented
> hey @techmannih could you into why some of the checks are failing?



> Lets see I am not quite sure why the checks are failing as well.

these are passed now

2024-10-03 05:52 UTC, ashmit-coder commented
Hey @techmannih , the titles for
1. Atinuke Oluwabamikemi Kayode
2. Aishat Muibudeen
3. Ankit Dash

are missing.

2024-10-03 06:16 UTC, thulieblack requested changes
@techmannih please make the changes

2024-10-03 06:16 UTC, thulieblack commented on config/speakers.json
> +			"title": "Founder and CEO at Polarizer Technologies",
```suggestion
			"title": "Co-founder, CTO at Specmatic",
```

2024-10-03 06:16 UTC, thulieblack commented on config/speakers.json
> +			"title": "Principal Developer Advocate, Office of the CTO at Solace",
```suggestion
			"title": "Principal Developer Advocate and Architect at Solace at Solace",
```

2024-10-03 06:16 UTC, thulieblack commented on config/speakers.json
> +			"title": "",
```suggestion
			"title": "Community Manager at AsyncAPI Initiative",
```

2024-10-03 06:16 UTC, thulieblack commented on config/speakers.json
> +			"title": "",
```suggestion
			"title": "Community Marketing Specialist at AsyncAPI Initiative",
```

2024-10-03 06:16 UTC, thulieblack commented on config/speakers.json
> +			"title": "",
```suggestion
			"title": "Full Stack Developer",
```

2024-10-03 06:16 UTC, thulieblack commented on config/speakers.json
> +			"title": "",
```suggestion
			"title": "Product Designer and UX Researcher",
```

2024-10-03 06:16 UTC, thulieblack commented on config/speakers.json
> +			"title": "Java Architect. Speaker. Building ZenWave 360°",
```suggestion
			"title": "Java Architect",
```

2024-10-03 06:16 UTC, thulieblack commented on config/speakers.json
> +			"title": "MSE in DS Student at the University of Pennsylvania",
```suggestion
			"title": "Software Engineer",
```

2024-10-03 07:06 UTC, techmannih commented
@ashmit-coder @thulieblack  please check now

2024-10-03 08:30 UTC, thulieblack commented
@techmannih, the images are not showing


https://github.com/user-attachments/assets/23614a2c-7d61-4b15-a9f8-b5c859e396ac

I suggest you download them, create a folder locally under `public/img/online-conf-images/` and reference them using the following path `/img/online-images/.....jpeg`

2024-10-04 07:43 UTC, techmannih commented
@ashmit-coder @thulieblack

2024-10-04 08:21 UTC, thulieblack commented
Thanks, @techmannih; I'll wait for @ashmit-coder's review first.

Please be patient, reviews take time

2024-10-04 08:27 UTC, techmannih commented
@thulieblack sure, thank you!

2024-10-04 08:43 UTC, ashmit-coder commented
Hey @techmannih could you try to use `.webp` format for the images instead of `jpeg` . We are looking forward to reduce load times of the conference website as well and this will be a great start to it!
If you are unable to do it, just use jpeg. 
Other than that the changes LGTM @thulieblack ! (Just verify the data from your end)

2024-10-04 08:44 UTC, ashmit-coder commented on config/speakers.json
> +			"title": "Founder and CEO at Polarizer Technologies",
just resolve these conseversations as well @techmannih .

2024-10-04 09:12 UTC, techmannih commented
@techmannih @thulieblack please check now

2024-10-04 09:33 UTC, ashmit-coder commented
LGTM!

2024-10-07 20:05 UTC, ashmit-coder commented
Hey @thulieblack ig the PR is ready to be merged!

2024-10-08 05:39 UTC, thulieblack approved these changes
Thanks @techmannih

2024-10-08 05:40 UTC, thulieblack commented
/rtm

2024-10-08 05:40 UTC, merged

2024-10-08 10:27 UTC, techmannih commented
@thulieblack please add Hacktoberfest-accepted label