fix: return to top arrow feature/button
asyncapi/conference-website pull request #477
Opened 2024-11-25 09:49 UTC by techmannih

**Description**
This PR implements a "Return to top" arrow feature/button to improve user navigation. When clicked, the button smoothly scrolls the page back to the top, enhancing the user experience by providing a quick way to navigate to the top of long pages.

**Related issue(s)**
Issue #475 
close #475

2024-11-27 08:49 UTC, ashmit-coder commented
@techmannih please make the button available in other pages as well. Also, use some different style of arrow.

2024-12-17 07:23 UTC, AceTheCreator requested changes
Awesome fix @techmannih 

I think the background should have the background of the button below and the arrow should be white, to keep the UI consistent. 

![AsyncAPI-Conference-12-17-2024_08_21_AM](https://github.com/user-attachments/assets/84966d92-a189-4446-982a-3a04091de332)

2025-01-14 08:49 UTC, ashmit-coder commented
is this pr active @techmannih ?

2025-01-14 09:05 UTC, ashmit-coder commented
> Yeah, I updated soon

Resolve Ace's request and update the branch

2025-01-28 17:52 UTC, AceTheCreator commented
@techmannih, sorry i'll have to close this PR, cuz there's already a pr close to completion implementing this :)

2025-01-28 17:52 UTC, closed without merging