fix: ticket section render issue using slider component
asyncapi/conference-website pull request #478
Opened 2024-11-26 11:17 UTC by toffee-k21

**Description**

fixes #395 
fixed card rendering issue in the Ticket section

2024-11-27 09:06 UTC, ashmit-coder requested changes
![image](https://github.com/user-attachments/assets/d69929fa-3eae-49c9-99bb-6992daa163f9)
@toffee-k21 the tickets are breaking in the on compressed view.

2024-11-27 09:07 UTC, ashmit-coder requested changes
Also add a test in the cypress test suite, for the changes you have made.

2024-11-28 13:52 UTC, toffee-k21 commented
> Also add a test in the cypress test suite, for the changes you have made.

Hey @ashmit-coder, I have made the changes you suggested and also added Cypress tests for the changes I made.

Additionally, there was an issue with the overflow of the slider component, which I have fixed. Below is the video regarding that

https://github.com/user-attachments/assets/7907fd28-919f-494e-ab79-ae3cccbc1e47

https://github.com/user-attachments/assets/3f18713c-171f-44da-8081-672d19e45bbb

2024-12-17 07:19 UTC, AceTheCreator requested changes
good work @toffee-k21, few suggested changes

- I noticed the venues on the landing is aligned to the left on desktop view
- I think you should remove the description in the ticket card and just keep it simple

2024-12-19 15:57 UTC, toffee-k21 commented
Thanks @AceTheCreator for your feedback, I have implemented what you suggested. Let me know if there's anything else you'd like me to adjust!

2025-01-02 11:37 UTC, ashmit-coder commented
> Thanks @AceTheCreator for your feedback, I have implemented what you suggested. Let me know if there's anything else you'd like me to adjust!

cc: @AceTheCreator

2025-01-28 17:51 UTC, AceTheCreator commented
@toffee-k21, sorry for the late response. Can you resolve the conflict in this PR

2025-01-29 10:06 UTC, closed without merging

2025-01-29 11:14 UTC, toffee-k21 commented
Hey @AceTheCreator, I had to create a new PR #547 due to sync issues. Let me know if everything looks good!