Fixed header and logo color distinction and added proper logo colors #484
asyncapi/conference-website pull request #493
Opened 2024-12-14 18:04 UTC by Tanmayshi

Fix: Darkened the header color to make the distinction between the header and logo clearer.
Improvement: Updated the logo colors to align with the proper color scheme for better visual clarity.
Additional Change: Enhanced the UI by improving the contrast between header and logo elements, making it more user-friendly.
Related issue(s)
Fixes #484

2024-12-15 05:25 UTC, TenzDelek commented on components/Sponsors/sponsors.js
> +				<Heading typeStyle='heading-md' className='text-gray-800 mt-10 sm:text-2xl sm:mt-5'>Event and Host Sponsor</Heading>
a lighter shade is appreciated. (also try with stale)

2024-12-15 05:25 UTC, TenzDelek commented on pages/index.js
> +				<Sponsors eventSponsors={[{image:'/img/apidays_2.webp',websiteUrl:"https://www.apidays.global/"}]} financialSponsor={[{image:"/img/graviteeIo_1.png" , websiteUrl: "https://www.gravitee.io/",class
I believe there is no need to change the logo, the logo are taken from the official branding i believe

2024-12-17 07:12 UTC, AceTheCreator requested changes
Kindly fix your PR title as suggested by the bot :)

2024-12-17 11:03 UTC, Tanmayshi commented
"Hi @AceTheCreator,
I have updated the PR title as per the Conventional Commit guidelines (fix: distinguish header and logo colors, added proper logo styles). Please review the changes and let me know if there's anything else to address. 😊"

2024-12-19 18:41 UTC, AceTheCreator commented
> "Hi @AceTheCreator, I have updated the PR title as per the Conventional Commit guidelines (fix: distinguish header and logo colors, added proper logo styles). Please review the changes and let me know if there's anything else to address. 😊"

I think you should apply suggested changes from @TenzDelek 🤔

2024-12-19 23:12 UTC, closed without merging

2024-12-20 01:48 UTC, TenzDelek commented
I think the contributor don't want to work on this issue looking at the deleted branch. Therefore I will be taking the issue from here