style: enhance hover effect on venue card and map icon (Fixes #492)
asyncapi/conference-website pull request #495
Opened 2024-12-17 13:17 UTC by Tanmayshi

"Updated the hover effects on the venue card and map icon button to improve visual interaction:

Applied a smooth hover effect on the venue card for a more polished look.
Enhanced the hover effect on the map icon for better user interaction.
No data changes were made; only UI/UX improvements for smoother navigation."

This should now be clear and focused on the hover effect changes without any confusion. It also highlights the map icon interaction change. Let me kno

https://github.com/user-attachments/assets/4a7906ef-f38a-48f7-bd2f-94f7b654d41d

w if you'd like any further adjustments!

Fixes issue #492

2024-12-19 18:39 UTC, AceTheCreator requested changes
This looks really good @Tanmayshi 😍

Btw, Why's there changes in the /public/img? I don't think this is related to your PR

2025-01-02 11:42 UTC, ashmit-coder commented
> This looks really good @Tanmayshi 😍
> 
> Btw, Why's there changes in the /public/img? I don't think this is related to your PR

cc: @Tanmayshi

2025-01-28 17:49 UTC, AceTheCreator commented
@Tanmayshi, still interested in pushing this?

2025-03-09 11:51 UTC, AceTheCreator commented
Closing this PR, due to lack of response from contributor

2025-03-09 11:51 UTC, closed without merging